version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wweb-js-bot
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 491999732c0a1b21077d15d136fa674d
      MONGO_INITDB_DATABASE: root-db
